#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>

int main(void){

	const int16_t a_upperbound = 101;
	const int16_t a_lowerbound = 2;
	const int16_t b_upperbound = 101;
	const int16_t b_lowerbound = 2;

	const uint64_t rei = UINT32_MAX;
	bool* appeared = malloc(sizeof(bool) * rei);
	//memset(appeared, false, rei * sizeof(bool));

	for(uint8_t a = a_lowerbound; a < a_upperbound; a++){
		uint64_t res = a;   // insert first element
		for(uint8_t b = b_lowerbound; b < b_upperbound; b++){
			res *= a;
			appeared[res] = true;
		}
	}

	uint16_t count = 0;
	for(uint16_t i = 0; i < rei; i++)
		count += appeared[i];

	printf("%u distinct terms are in the sequence generated by a^b\n", count);

	return EXIT_SUCCESS;
}
